Repository OpenTabletDriver/OpenTabletDriver.Web, pull requests merged in 2022-01, with the labels that each got.

#29 Add Administrator account warning on Window FAQ.
  OpenTabletDriver.Web/Views/Wiki/FAQ/Windows.cshtml
Labels: enhancement, wiki

#34 Adjust the release card.
  OpenTabletDriver.Web/Views/Shared/Release/_ReleaseCard.cshtml
Labels: enhancement

#38 Add Windows install upgrade note
  OpenTabletDriver.Web/Views/Wiki/Install/Windows.cshtml
Labels: wiki

#45 Add basic Configurations documentation
  OpenTabletDriver.Web/Views/Wiki/Development/Configurations.cshtml
  OpenTabletDriver.Web/Views/Wiki/Index.cshtml
Labels: documentation

#49 Update macOS install guide
  OpenTabletDriver.Web/Views/Wiki/Install/MacOS.cshtml
Labels: documentation

#50 Fix Linux FAQ virtual device initialization not being a nav item
  OpenTabletDriver.Web/Views/Wiki/FAQ/Linux.cshtml
Labels: bug, wiki

#52 Cache service responses, fix dependency injection
  OpenTabletDriver.Web.Core/DependencyInjectionExtensions.cs
  OpenTabletDriver.Web.Core/GitHub/API/GitHubAssetGetResponse.cs
  OpenTabletDriver.Web.Core/GitHub/API/GitHubAssetResponse.cs
  OpenTabletDriver.Web.Core/GitHub/API/GitHubAssetRestClient.cs
  OpenTabletDriver.Web.Core/GitHub/GitHubRelease.cs
  OpenTabletDriver.Web.Core/GitHub/GitHubReleaseAsset.cs
  OpenTabletDriver.Web.Core/GitHub/GitHubWorkflowArtifact.cs
  OpenTabletDriver.Web.Core/GitHub/GitHubWorkflowRun.cs
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubCore.cs
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubReleaseService.cs
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubRepositoryService.cs
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubTabletService.cs
  OpenTabletDriver.Web.Core/OpenTabletDriver.Web.Core.csproj
  OpenTabletDriver.Web.Core/Plugins/GitHubPluginMetadataService.cs
  OpenTabletDriver.Web.Core/Services/IPluginMetadataService.cs
  OpenTabletDriver.Web.Core/Services/IReleaseService.cs
  OpenTabletDriver.Web.Core/Services/IRepositoryService.cs
  OpenTabletDriver.Web.Core/Services/ITabletService.cs
  OpenTabletDriver.Web.Core/Utilities/RestClientAdvanced.cs
  OpenTabletDriver.Web/Controllers/TabletsController.cs
  OpenTabletDriver.Web/OpenTabletDriver.Web.csproj
  OpenTabletDriver.Web/Startup.cs
  default.nix
  deps.nix
Labels: bug, enhancement

#53 Increase cache expiration interval
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubReleaseService.cs
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubRepositoryService.cs
  OpenTabletDriver.Web.Core/GitHub/Services/GitHubTabletService.cs
  OpenTabletDriver.Web.Core/Plugins/GitHubPluginMetadataService.cs
  OpenTabletDriver.Web.Core/Utilities/RestClientAdvanced.cs
Labels: enhancement

#54 Clean up Views and Controllers
  OpenTabletDriver.Web/Controllers/DiscordController.cs
  OpenTabletDriver.Web/Controllers/GitHubController.cs
  OpenTabletDriver.Web/Controllers/HomeController.cs
  OpenTabletDriver.Web/Views/Shared/_Layout.cshtml
  OpenTabletDriver.Web/Views/Shared/_LayoutHeader.cshtml
  OpenTabletDriver.Web/Views/Shared/_Styles.cshtml
  OpenTabletDriver.Web/Views/Wiki/_WikiLayout.cshtml
Labels: enhancement
